module.exports = {
    errorOpenFile: 'Open any file to execute command',
    errorFileNotSupport : 'This file is not supported for this command',
    terminalName : 'SFDevTools',
    errorNotvalidWorkspace: 'Is not a valid workspace',
    noDataFound: 'No data found in text editor, add some JSON data to format',
    deployErrorMsg: 'Error: Deployment failed, Check errors',
    deploySuccessMsg: 'Success: Deployed successfully',
    retrieveErrorMsg: 'Error: Retrieve failed, Check errors',
    retrieveSuccessMsg: 'Success: Retrieved from org successfully',
    outputChannelErrorL1: '==== Deploy/ Retrieve Error Log ====',
    outputChannelErrorL2: 'FILE NAME                           ERRORS',
    outputChannelErrorL3: '──────────────────────────────────  ─────────────────────────────────',
    outputChannelSuccessL1: '==== Deploy/ Retrieve Success Log ====',
    outputChannelSuccessL2: 'FILE NAME',
    outputChannelSuccessL3: '──────────────────────────────────',
    cancelExecution: 'Execution cancelled',
    logErrorMsg: 'ERROR: Something went Wrong',
    mdTypePlaceHolder: 'Select a metadat type to retrieve',
    mdNamePlaceHolder: 'Enter API name of the component to retrieve',
    openInOrgSuccessMsg: 'Success: Opened file in Org',
    soqlErrorMsg: 'Something went wrong, while fetching data from org',
    soqlErrorNoDataMsg: 'We did not found requested component in org',
    completedExecution: 'Completed Execution at '
}