module.exports = {
    errorOpenFile: 'Open any file to execute command',
    errorFileNotSupport : 'This file is not supported for this command',
    terminalName : 'SFDevTools',
    errorNotvalidWorkspace: 'Is not a valid workspace',
    noDataFound: 'No data found in text editor, add some JSON data to format',
    deployErrorMsg: 'Error: Deployment failed, Check errors',
    deploySuccessMsg: 'Success: Deployed successfully',
    retrieveErrorMsg: 'Error: Retrieve failed, Check errors',
    retrieveSuccessMsg: 'Success: Retrieved from org successfully',
    outputChannelL1: '==== Deploy/ Retrieve Errors ====',
    outputChannelL2: 'FILE NAME                           ERRORS',
    outputChannelL3: '──────────────────────────────────  ─────────────────────────────────',
    cancelExecution: 'Execution cancelled',
    logErrorMsg: 'ERROR: Something went Wrong',
    mdTypePlaceHolder: 'Select a metadat type to retrieve',
    mdNamePlaceHolder: 'Enter API name of the component to retrieve',
    openInOrgSuccessMsg: 'Success: Opened file in Org',
}